### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by CyberGamer224466** [PaoloAmoroso/Alenia-C-27J-Spartan#1]
I am getting this issue when trying to use your C-27J

![image](https://github.com/user-attachments/assets/77a08527-0e41-4399-8a2e-96a4d17e63c7)

tested on next and stable on windows 10

**Comment by PaoloAmoroso** [comment]
This issue has been resolved.

**Comment by CyberGamer224466** [comment]
It's still present on the newest update. It only happens on the 2020.4.
